titles.connections="Connections";
pageGuides.connections={label:"Tools and permissions",purpose:"Connect external services and control exactly what Nova employees may do.",action:"Review tool access",target:"connections"};
let novaConnections=[];
const capabilityHelp={read:"View information only",write:"Create branches and pull requests",deploy:"Deploy approved production changes",draft:"Prepare content without sending",send:"Send founder-approved messages",refund:"Issue approved customer refunds",spend:"Create approved charges or purchases",publish:"Publish approved campaigns"};
function connectionIcon(id){return{github:"GH",email:"@",payments:"$",marketing:"↗"}[id]||"⌁"}
function currentPermissions(){return Object.fromEntries(novaConnections.map(connection=>[connection.id,{...connection.capabilities}]))}
function renderConnections(){
  if(!$("connectionGrid"))return;const configured=novaConnections.filter(item=>item.configured).length;$("connectionsSummary").textContent=`${configured} of ${novaConnections.length} connected`;
  $("connectionGrid").innerHTML=novaConnections.map(connection=>`<article class="tool-connection"><header><div><span class="tool-logo">${connectionIcon(connection.id)}</span><span><h3>${escapeHtml(connection.name)}</h3><p>${escapeHtml(connection.purpose)}</p></span></div><em class="connection-state ${connection.configured?"connected":"disconnected"}">${connection.configured?"CONNECTED":"NOT CONNECTED"}</em></header><div class="capability-list">${Object.entries(connection.capabilities).map(([capability,enabled])=>`<div class="capability-row"><span><b>${escapeHtml(capability)}</b><small>${escapeHtml(capabilityHelp[capability]||"Scoped tool permission")}</small></span><button type="button" class="permission-toggle ${enabled?"on":""}" role="switch" aria-checked="${enabled}" aria-label="Allow ${escapeHtml(connection.name)} ${escapeHtml(capability)}" data-tool="${escapeHtml(connection.id)}" data-capability="${escapeHtml(capability)}"></button></div>`).join("")}</div><footer class="tool-footer"><span>${connection.configured?"Short-lived server token · browser never sees credentials":"Setup required before employees can use this tool"}</span>${connection.id==="github"?'<button class="secondary" type="button" data-verify-github>Verify GitHub</button>':""}</footer></article>`).join("");
  $("connectionGrid").querySelectorAll("[data-tool]").forEach(button=>button.onclick=async()=>{const connection=novaConnections.find(item=>item.id===button.dataset.tool),capability=button.dataset.capability,next=!connection.capabilities[capability],highImpact=new Set(["write","deploy","send","refund","spend","publish"]).has(capability);if(next&&highImpact&&!confirm(`Enable ${connection.name} ${capability}? Nova will still require founder approval for each external action.`))return;connection.capabilities[capability]=next;try{const response=await authFetch("/api/tool-connections/permissions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId:currentWorkspaceId,permissions:currentPermissions()})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Permissions could not be saved");novaConnections.forEach(item=>item.capabilities=result.permissions[item.id]);renderConnections();toast("Tool permissions saved");}catch(error){connection.capabilities[capability]=!next;renderConnections();toast(error.message)}});
  $("connectionGrid").querySelector("[data-verify-github]")?.addEventListener("click",async event=>{const button=event.currentTarget;button.disabled=true;button.textContent="Verifying…";try{const response=await authFetch("/api/tool-connections/github/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId:currentWorkspaceId})}),result=await response.json();if(!response.ok)throw new Error(result.error||"GitHub could not be verified");toast(`GitHub connected · ${result.repositories} repositories visible`);}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent="Verify GitHub";}});
}
async function loadConnections(){if(!currentWorkspaceId)return;try{const response=await authFetch(`/api/tool-connections?workspace=${encodeURIComponent(currentWorkspaceId)}`),result=await response.json();if(!response.ok)throw new Error(result.error||"Connections could not load");novaConnections=result.connections||[];renderConnections();}catch(error){$("connectionsSummary").textContent="Connection service unavailable";toast(error.message)}}
$("copyGitHubSetup").onclick=async()=>{await navigator.clipboard.writeText("vercel connect create github --name nova-ai");toast("GitHub setup command copied")};
const showBeforeConnections=show;show=view=>{showBeforeConnections(view);if(view==="connections")loadConnections();};
