(()=>{
  const form=$("kpiForm"),source=$("kpiSource"),current=$("kpiCurrent"),name=$("kpiName"),unit=$("kpiUnit");
  function sourceChanged(){const automatic=source.value!=="manual",defaults=kpiSourceDefaults[source.value];current.disabled=automatic;current.value=automatic?"0":current.value;if(defaults){if(!name.value.trim()||Object.values(kpiSourceDefaults).some(item=>item[0]===name.value))name.value=defaults[0];if(!unit.value.trim()||Object.values(kpiSourceDefaults).some(item=>item[1]===unit.value))unit.value=defaults[1];}}
  source.onchange=sourceChanged;
  form.onsubmit=async event=>{event.preventDefault();const target=Number($("kpiTarget").value),manualCurrent=Number(current.value),dataSource=source.value;if(!Number.isFinite(target)||target<=0||!Number.isFinite(manualCurrent))return toast("Enter valid current and target values");const item={id:crypto.randomUUID?.()||`kpi-${Date.now()}`,name:name.value.trim(),current:dataSource==="manual"?manualCurrent:0,target,unit:unit.value.trim(),source:dataSource,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),history:dataSource==="manual"?[{value:manualCurrent,at:new Date().toISOString()}]:[]};item.current=metricCurrent(item);state.kpis=[item,...(state.kpis||[])].slice(0,12);await save();form.reset();current.value="0";$("kpiTarget").value="10";source.value="manual";current.disabled=false;render();toast(dataSource==="manual"?"KPI added to the company scoreboard":"Live KPI connected to Nova data");};
  const originalPublishing=window.loadPublishing;window.loadPublishing=async()=>{publishingStats={views:0,signups:0};await originalPublishing();publishingStats={views:Number($("pageViews").textContent||0),signups:Number($("pageSignups").textContent||0)};renderGoals();};
  const originalMemoryContext=companyMemoryContext;companyMemoryContext=()=>{const context=originalMemoryContext();return{...context,kpis:(state.kpis||[]).map(item=>({name:item.name,current:metricCurrent(item),target:item.target,unit:item.unit,source:item.source||"manual"})).slice(0,12)};};
  window.addEventListener("nova-validation-stats",()=>renderGoals());
})();
